version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    groups:
      kubernetes-dependencies:
        patterns:
          - "k8s.io/*"
          - "sigs.k8s.io/*"
  - package-ecosystem: docker
    directory: /cmd
    schedule:
      interval: weekly
    groups:
      docker-images:
        patterns:
          - "*"
  - package-ecosystem: docker
    directory: /cmd/worker
    schedule:
      interval: weekly
    groups:
      docker-images:
        patterns:
          - "*"
