FROM golang:1.17 as builder

WORKDIR /workspace
COPY go.mod go.mod
COPY go.sum go.sum
RUN go mod download

COPY worker/ worker/
COPY apis/ apis/
COPY pkg/ pkg/

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -o bin/worker worker/main.go

FROM registry.undistro.io/gcr/distroless/static:nonroot
WORKDIR /
COPY --from=builder /workspace/bin/worker /usr/local/bin/
USER 65533:65533

ENTRYPOINT ["/usr/local/bin/worker"]
