// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/undistro/zora/api/zora/v1alpha2"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// CustomCheckLister helps list CustomChecks.
// All objects returned here must be treated as read-only.
type CustomCheckLister interface {
	// List lists all CustomChecks in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.CustomCheck, err error)
	// CustomChecks returns an object that can list and get CustomChecks.
	CustomChecks(namespace string) CustomCheckNamespaceLister
	CustomCheckListerExpansion
}

// customCheckLister implements the CustomCheckLister interface.
type customCheckLister struct {
	indexer cache.Indexer
}

// NewCustomCheckLister returns a new CustomCheckLister.
func NewCustomCheckLister(indexer cache.Indexer) CustomCheckLister {
	return &customCheckLister{indexer: indexer}
}

// List lists all CustomChecks in the indexer.
func (s *customCheckLister) List(selector labels.Selector) (ret []*v1alpha2.CustomCheck, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.CustomCheck))
	})
	return ret, err
}

// CustomChecks returns an object that can list and get CustomChecks.
func (s *customCheckLister) CustomChecks(namespace string) CustomCheckNamespaceLister {
	return customCheckNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// CustomCheckNamespaceLister helps list and get CustomChecks.
// All objects returned here must be treated as read-only.
type CustomCheckNamespaceLister interface {
	// List lists all CustomChecks in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha2.CustomCheck, err error)
	// Get retrieves the CustomCheck from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha2.CustomCheck, error)
	CustomCheckNamespaceListerExpansion
}

// customCheckNamespaceLister implements the CustomCheckNamespaceLister
// interface.
type customCheckNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all CustomChecks in the indexer for a given namespace.
func (s customCheckNamespaceLister) List(selector labels.Selector) (ret []*v1alpha2.CustomCheck, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.CustomCheck))
	})
	return ret, err
}

// Get retrieves the CustomCheck from the indexer for a given namespace and name.
func (s customCheckNamespaceLister) Get(name string) (*v1alpha2.CustomCheck, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("customcheck"), name)
	}
	return obj.(*v1alpha2.CustomCheck), nil
}
