// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

// CustomCheckListerExpansion allows custom methods to be added to
// CustomCheckLister.
type CustomCheckListerExpansion interface{}

// CustomCheckNamespaceListerExpansion allows custom methods to be added to
// CustomCheckNamespaceLister.
type CustomCheckNamespaceListerExpansion interface{}

// VulnerabilityReportListerExpansion allows custom methods to be added to
// VulnerabilityReportLister.
type VulnerabilityReportListerExpansion interface{}

// VulnerabilityReportNamespaceListerExpansion allows custom methods to be added to
// VulnerabilityReportNamespaceLister.
type VulnerabilityReportNamespaceListerExpansion interface{}
