// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/undistro/zora/api/zora/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	testing "k8s.io/client-go/testing"
)

// FakeClusterScans implements ClusterScanInterface
type FakeClusterScans struct {
	Fake *FakeZoraV1alpha1
	ns   string
}

var clusterscansResource = schema.GroupVersionResource{Group: "zora", Version: "v1alpha1", Resource: "clusterscans"}

var clusterscansKind = schema.GroupVersionKind{Group: "zora", Version: "v1alpha1", Kind: "ClusterScan"}

// Get takes name of the clusterScan, and returns the corresponding clusterScan object, and an error if there is any.
func (c *FakeClusterScans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterScan, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterscansResource, c.ns, name), &v1alpha1.ClusterScan{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterScan), err
}

// List takes label and field selectors, and returns the list of ClusterScans that match those selectors.
func (c *FakeClusterScans) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterScanList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterscansResource, clusterscansKind, c.ns, opts), &v1alpha1.ClusterScanList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterScanList{ListMeta: obj.(*v1alpha1.ClusterScanList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterScanList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}
