// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/getupio-undistro/zora/apis/zora/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeClusterIssueOverrides implements ClusterIssueOverrideInterface
type FakeClusterIssueOverrides struct {
	Fake *FakeZoraV1alpha1
	ns   string
}

var clusterissueoverridesResource = schema.GroupVersionResource{Group: "zora", Version: "v1alpha1", Resource: "clusterissueoverrides"}

var clusterissueoverridesKind = schema.GroupVersionKind{Group: "zora", Version: "v1alpha1", Kind: "ClusterIssueOverride"}

// Get takes name of the clusterIssueOverride, and returns the corresponding clusterIssueOverride object, and an error if there is any.
func (c *FakeClusterIssueOverrides) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterIssueOverride, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(clusterissueoverridesResource, c.ns, name), &v1alpha1.ClusterIssueOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterIssueOverride), err
}

// List takes label and field selectors, and returns the list of ClusterIssueOverrides that match those selectors.
func (c *FakeClusterIssueOverrides) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterIssueOverrideList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(clusterissueoverridesResource, clusterissueoverridesKind, c.ns, opts), &v1alpha1.ClusterIssueOverrideList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ClusterIssueOverrideList{ListMeta: obj.(*v1alpha1.ClusterIssueOverrideList).ListMeta}
	for _, item := range obj.(*v1alpha1.ClusterIssueOverrideList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested clusterIssueOverrides.
func (c *FakeClusterIssueOverrides) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(clusterissueoverridesResource, c.ns, opts))

}

// Create takes the representation of a clusterIssueOverride and creates it.  Returns the server's representation of the clusterIssueOverride, and an error, if there is any.
func (c *FakeClusterIssueOverrides) Create(ctx context.Context, clusterIssueOverride *v1alpha1.ClusterIssueOverride, opts v1.CreateOptions) (result *v1alpha1.ClusterIssueOverride, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(clusterissueoverridesResource, c.ns, clusterIssueOverride), &v1alpha1.ClusterIssueOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterIssueOverride), err
}

// Update takes the representation of a clusterIssueOverride and updates it. Returns the server's representation of the clusterIssueOverride, and an error, if there is any.
func (c *FakeClusterIssueOverrides) Update(ctx context.Context, clusterIssueOverride *v1alpha1.ClusterIssueOverride, opts v1.UpdateOptions) (result *v1alpha1.ClusterIssueOverride, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(clusterissueoverridesResource, c.ns, clusterIssueOverride), &v1alpha1.ClusterIssueOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterIssueOverride), err
}

// Delete takes name of the clusterIssueOverride and deletes it. Returns an error if one occurs.
func (c *FakeClusterIssueOverrides) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(clusterissueoverridesResource, c.ns, name, opts), &v1alpha1.ClusterIssueOverride{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeClusterIssueOverrides) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(clusterissueoverridesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ClusterIssueOverrideList{})
	return err
}

// Patch applies the patch and returns the patched clusterIssueOverride.
func (c *FakeClusterIssueOverrides) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterIssueOverride, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(clusterissueoverridesResource, c.ns, name, pt, data, subresources...), &v1alpha1.ClusterIssueOverride{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ClusterIssueOverride), err
}
