// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/undistro/zora/pkg/clientset/versioned/typed/zora/v1alpha2"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeZoraV1alpha2 struct {
	*testing.Fake
}

func (c *FakeZoraV1alpha2) CustomChecks(namespace string) v1alpha2.CustomCheckInterface {
	return &FakeCustomChecks{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeZoraV1alpha2) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
