// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha2 "github.com/undistro/zora/api/zora/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeCustomChecks implements CustomCheckInterface
type FakeCustomChecks struct {
	Fake *FakeZoraV1alpha2
	ns   string
}

var customchecksResource = v1alpha2.SchemeGroupVersion.WithResource("customchecks")

var customchecksKind = v1alpha2.SchemeGroupVersion.WithKind("CustomCheck")

// Get takes name of the customCheck, and returns the corresponding customCheck object, and an error if there is any.
func (c *FakeCustomChecks) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha2.CustomCheck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(customchecksResource, c.ns, name), &v1alpha2.CustomCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.CustomCheck), err
}

// List takes label and field selectors, and returns the list of CustomChecks that match those selectors.
func (c *FakeCustomChecks) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha2.CustomCheckList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(customchecksResource, customchecksKind, c.ns, opts), &v1alpha2.CustomCheckList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.CustomCheckList{ListMeta: obj.(*v1alpha2.CustomCheckList).ListMeta}
	for _, item := range obj.(*v1alpha2.CustomCheckList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested customChecks.
func (c *FakeCustomChecks) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(customchecksResource, c.ns, opts))

}

// Create takes the representation of a customCheck and creates it.  Returns the server's representation of the customCheck, and an error, if there is any.
func (c *FakeCustomChecks) Create(ctx context.Context, customCheck *v1alpha2.CustomCheck, opts v1.CreateOptions) (result *v1alpha2.CustomCheck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(customchecksResource, c.ns, customCheck), &v1alpha2.CustomCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.CustomCheck), err
}

// Update takes the representation of a customCheck and updates it. Returns the server's representation of the customCheck, and an error, if there is any.
func (c *FakeCustomChecks) Update(ctx context.Context, customCheck *v1alpha2.CustomCheck, opts v1.UpdateOptions) (result *v1alpha2.CustomCheck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(customchecksResource, c.ns, customCheck), &v1alpha2.CustomCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.CustomCheck), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeCustomChecks) UpdateStatus(ctx context.Context, customCheck *v1alpha2.CustomCheck, opts v1.UpdateOptions) (*v1alpha2.CustomCheck, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(customchecksResource, "status", c.ns, customCheck), &v1alpha2.CustomCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.CustomCheck), err
}

// Delete takes name of the customCheck and deletes it. Returns an error if one occurs.
func (c *FakeCustomChecks) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(customchecksResource, c.ns, name, opts), &v1alpha2.CustomCheck{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeCustomChecks) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(customchecksResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha2.CustomCheckList{})
	return err
}

// Patch applies the patch and returns the patched customCheck.
func (c *FakeCustomChecks) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha2.CustomCheck, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(customchecksResource, c.ns, name, pt, data, subresources...), &v1alpha2.CustomCheck{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.CustomCheck), err
}
