// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	zorav1alpha1 "github.com/undistro/zora/api/zora/v1alpha1"
	versioned "github.com/undistro/zora/pkg/clientset/versioned"
	internalinterfaces "github.com/undistro/zora/pkg/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/undistro/zora/pkg/listers/zora/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ClusterScanInformer provides access to a shared informer and lister for
// ClusterScans.
type ClusterScanInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ClusterScanLister
}

type clusterScanInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewClusterScanInformer constructs a new informer for ClusterScan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewClusterScanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredClusterScanInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredClusterScanInformer constructs a new informer for ClusterScan type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredClusterScanInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZoraV1alpha1().ClusterScans(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZoraV1alpha1().ClusterScans(namespace).Watch(context.TODO(), options)
			},
		},
		&zorav1alpha1.ClusterScan{},
		resyncPeriod,
		indexers,
	)
}

func (f *clusterScanInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredClusterScanInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *clusterScanInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&zorav1alpha1.ClusterScan{}, f.defaultInformer)
}

func (f *clusterScanInformer) Lister() v1alpha1.ClusterScanLister {
	return v1alpha1.NewClusterScanLister(f.Informer().GetIndexer())
}
