// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	internalinterfaces "github.com/undistro/zora/pkg/informers/externalversions/internalinterfaces"
)

// Interface provides access to all the informers in this group version.
type Interface interface {
	// Clusters returns a ClusterInformer.
	Clusters() ClusterInformer
	// ClusterIssues returns a ClusterIssueInformer.
	ClusterIssues() ClusterIssueInformer
	// ClusterScans returns a ClusterScanInformer.
	ClusterScans() ClusterScanInformer
	// CustomChecks returns a CustomCheckInformer.
	CustomChecks() CustomCheckInformer
	// Plugins returns a PluginInformer.
	Plugins() PluginInformer
	// VulnerabilityReports returns a VulnerabilityReportInformer.
	VulnerabilityReports() VulnerabilityReportInformer
}

type version struct {
	factory          internalinterfaces.SharedInformerFactory
	namespace        string
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// New returns a new Interface.
func New(f internalinterfaces.SharedInformerFactory, namespace string, tweakListOptions internalinterfaces.TweakListOptionsFunc) Interface {
	return &version{factory: f, namespace: namespace, tweakListOptions: tweakListOptions}
}

// Clusters returns a ClusterInformer.
func (v *version) Clusters() ClusterInformer {
	return &clusterInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ClusterIssues returns a ClusterIssueInformer.
func (v *version) ClusterIssues() ClusterIssueInformer {
	return &clusterIssueInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// ClusterScans returns a ClusterScanInformer.
func (v *version) ClusterScans() ClusterScanInformer {
	return &clusterScanInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// CustomChecks returns a CustomCheckInformer.
func (v *version) CustomChecks() CustomCheckInformer {
	return &customCheckInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// Plugins returns a PluginInformer.
func (v *version) Plugins() PluginInformer {
	return &pluginInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}

// VulnerabilityReports returns a VulnerabilityReportInformer.
func (v *version) VulnerabilityReports() VulnerabilityReportInformer {
	return &vulnerabilityReportInformer{factory: v.factory, namespace: v.namespace, tweakListOptions: v.tweakListOptions}
}
