// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/getupio-undistro/snitch/pkg/clientset/versioned/typed/snitch/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeSnitchV1alpha1 struct {
	*testing.Fake
}

func (c *FakeSnitchV1alpha1) Clusters(namespace string) v1alpha1.ClusterInterface {
	return &FakeClusters{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeSnitchV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
