// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ClusterListerExpansion allows custom methods to be added to
// ClusterLister.
type ClusterListerExpansion interface{}

// ClusterNamespaceListerExpansion allows custom methods to be added to
// ClusterNamespaceLister.
type ClusterNamespaceListerExpansion interface{}

// ClusterIssueListerExpansion allows custom methods to be added to
// ClusterIssueLister.
type ClusterIssueListerExpansion interface{}

// ClusterIssueNamespaceListerExpansion allows custom methods to be added to
// ClusterIssueNamespaceLister.
type ClusterIssueNamespaceListerExpansion interface{}

// ClusterScanListerExpansion allows custom methods to be added to
// ClusterScanLister.
type ClusterScanListerExpansion interface{}

// ClusterScanNamespaceListerExpansion allows custom methods to be added to
// ClusterScanNamespaceLister.
type ClusterScanNamespaceListerExpansion interface{}

// CustomCheckListerExpansion allows custom methods to be added to
// CustomCheckLister.
type CustomCheckListerExpansion interface{}

// CustomCheckNamespaceListerExpansion allows custom methods to be added to
// CustomCheckNamespaceLister.
type CustomCheckNamespaceListerExpansion interface{}

// PluginListerExpansion allows custom methods to be added to
// PluginLister.
type PluginListerExpansion interface{}

// PluginNamespaceListerExpansion allows custom methods to be added to
// PluginNamespaceLister.
type PluginNamespaceListerExpansion interface{}

// VulnerabilityReportListerExpansion allows custom methods to be added to
// VulnerabilityReportLister.
type VulnerabilityReportListerExpansion interface{}

// VulnerabilityReportNamespaceListerExpansion allows custom methods to be added to
// VulnerabilityReportNamespaceLister.
type VulnerabilityReportNamespaceListerExpansion interface{}
