// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	"context"
	time "time"

	zorav1alpha2 "github.com/undistro/zora/api/zora/v1alpha2"
	versioned "github.com/undistro/zora/pkg/clientset/versioned"
	internalinterfaces "github.com/undistro/zora/pkg/informers/externalversions/internalinterfaces"
	v1alpha2 "github.com/undistro/zora/pkg/listers/zora/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// CustomCheckInformer provides access to a shared informer and lister for
// CustomChecks.
type CustomCheckInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.CustomCheckLister
}

type customCheckInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewCustomCheckInformer constructs a new informer for CustomCheck type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewCustomCheckInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredCustomCheckInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredCustomCheckInformer constructs a new informer for CustomCheck type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredCustomCheckInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZoraV1alpha2().CustomChecks(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ZoraV1alpha2().CustomChecks(namespace).Watch(context.TODO(), options)
			},
		},
		&zorav1alpha2.CustomCheck{},
		resyncPeriod,
		indexers,
	)
}

func (f *customCheckInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredCustomCheckInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *customCheckInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&zorav1alpha2.CustomCheck{}, f.defaultInformer)
}

func (f *customCheckInformer) Lister() v1alpha2.CustomCheckLister {
	return v1alpha2.NewCustomCheckLister(f.Informer().GetIndexer())
}
