// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/getupio-undistro/zora/apis/zora/v1alpha1"
	scheme "github.com/getupio-undistro/zora/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterIssueOverridesGetter has a method to return a ClusterIssueOverrideInterface.
// A group's client should implement this interface.
type ClusterIssueOverridesGetter interface {
	ClusterIssueOverrides(namespace string) ClusterIssueOverrideInterface
}

// ClusterIssueOverrideInterface has methods to work with ClusterIssueOverride resources.
type ClusterIssueOverrideInterface interface {
	Create(ctx context.Context, clusterIssueOverride *v1alpha1.ClusterIssueOverride, opts v1.CreateOptions) (*v1alpha1.ClusterIssueOverride, error)
	Update(ctx context.Context, clusterIssueOverride *v1alpha1.ClusterIssueOverride, opts v1.UpdateOptions) (*v1alpha1.ClusterIssueOverride, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterIssueOverride, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterIssueOverrideList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterIssueOverride, err error)
	ClusterIssueOverrideExpansion
}

// clusterIssueOverrides implements ClusterIssueOverrideInterface
type clusterIssueOverrides struct {
	client rest.Interface
	ns     string
}

// newClusterIssueOverrides returns a ClusterIssueOverrides
func newClusterIssueOverrides(c *ZoraV1alpha1Client, namespace string) *clusterIssueOverrides {
	return &clusterIssueOverrides{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterIssueOverride, and returns the corresponding clusterIssueOverride object, and an error if there is any.
func (c *clusterIssueOverrides) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterIssueOverride, err error) {
	result = &v1alpha1.ClusterIssueOverride{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterissueoverrides").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterIssueOverrides that match those selectors.
func (c *clusterIssueOverrides) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterIssueOverrideList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterIssueOverrideList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterissueoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterIssueOverrides.
func (c *clusterIssueOverrides) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterissueoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterIssueOverride and creates it.  Returns the server's representation of the clusterIssueOverride, and an error, if there is any.
func (c *clusterIssueOverrides) Create(ctx context.Context, clusterIssueOverride *v1alpha1.ClusterIssueOverride, opts v1.CreateOptions) (result *v1alpha1.ClusterIssueOverride, err error) {
	result = &v1alpha1.ClusterIssueOverride{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterissueoverrides").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterIssueOverride).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterIssueOverride and updates it. Returns the server's representation of the clusterIssueOverride, and an error, if there is any.
func (c *clusterIssueOverrides) Update(ctx context.Context, clusterIssueOverride *v1alpha1.ClusterIssueOverride, opts v1.UpdateOptions) (result *v1alpha1.ClusterIssueOverride, err error) {
	result = &v1alpha1.ClusterIssueOverride{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterissueoverrides").
		Name(clusterIssueOverride.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterIssueOverride).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterIssueOverride and deletes it. Returns an error if one occurs.
func (c *clusterIssueOverrides) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterissueoverrides").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterIssueOverrides) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterissueoverrides").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterIssueOverride.
func (c *clusterIssueOverrides) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterIssueOverride, err error) {
	result = &v1alpha1.ClusterIssueOverride{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterissueoverrides").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
