// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/undistro/zora/api/zora/v1alpha1"
	scheme "github.com/undistro/zora/pkg/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// ClusterScansGetter has a method to return a ClusterScanInterface.
// A group's client should implement this interface.
type ClusterScansGetter interface {
	ClusterScans(namespace string) ClusterScanInterface
}

// ClusterScanInterface has methods to work with ClusterScan resources.
type ClusterScanInterface interface {
	Create(ctx context.Context, clusterScan *v1alpha1.ClusterScan, opts v1.CreateOptions) (*v1alpha1.ClusterScan, error)
	Update(ctx context.Context, clusterScan *v1alpha1.ClusterScan, opts v1.UpdateOptions) (*v1alpha1.ClusterScan, error)
	UpdateStatus(ctx context.Context, clusterScan *v1alpha1.ClusterScan, opts v1.UpdateOptions) (*v1alpha1.ClusterScan, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.ClusterScan, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.ClusterScanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterScan, err error)
	ClusterScanExpansion
}

// clusterScans implements ClusterScanInterface
type clusterScans struct {
	client rest.Interface
	ns     string
}

// newClusterScans returns a ClusterScans
func newClusterScans(c *ZoraV1alpha1Client, namespace string) *clusterScans {
	return &clusterScans{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the clusterScan, and returns the corresponding clusterScan object, and an error if there is any.
func (c *clusterScans) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ClusterScan, err error) {
	result = &v1alpha1.ClusterScan{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterscans").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of ClusterScans that match those selectors.
func (c *clusterScans) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ClusterScanList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.ClusterScanList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("clusterscans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested clusterScans.
func (c *clusterScans) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("clusterscans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a clusterScan and creates it.  Returns the server's representation of the clusterScan, and an error, if there is any.
func (c *clusterScans) Create(ctx context.Context, clusterScan *v1alpha1.ClusterScan, opts v1.CreateOptions) (result *v1alpha1.ClusterScan, err error) {
	result = &v1alpha1.ClusterScan{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("clusterscans").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterScan).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a clusterScan and updates it. Returns the server's representation of the clusterScan, and an error, if there is any.
func (c *clusterScans) Update(ctx context.Context, clusterScan *v1alpha1.ClusterScan, opts v1.UpdateOptions) (result *v1alpha1.ClusterScan, err error) {
	result = &v1alpha1.ClusterScan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterscans").
		Name(clusterScan.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterScan).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *clusterScans) UpdateStatus(ctx context.Context, clusterScan *v1alpha1.ClusterScan, opts v1.UpdateOptions) (result *v1alpha1.ClusterScan, err error) {
	result = &v1alpha1.ClusterScan{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("clusterscans").
		Name(clusterScan.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(clusterScan).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the clusterScan and deletes it. Returns an error if one occurs.
func (c *clusterScans) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterscans").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *clusterScans) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("clusterscans").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched clusterScan.
func (c *clusterScans) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ClusterScan, err error) {
	result = &v1alpha1.ClusterScan{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("clusterscans").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
