// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

type ClusterExpansion interface{}

type ClusterIssueExpansion interface{}

type ClusterIssueOverrideExpansion interface{}

type ClusterScanExpansion interface{}
